# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [2]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 

import numpy as np

# Let's define a one-dimensional array 

list_1 =[20,40,30,90,120,200,300,500,600]
list_1

[20, 40, 30, 90, 120, 200, 300, 500, 600]

In [3]:
# Let's create a numpy array from the list "my_list"
mynparray = np.array(list_1)
mynparray

array([ 20,  40,  30,  90, 120, 200, 300, 500, 600])

In [4]:
type(mynparray)

numpy.ndarray

In [6]:
# Multi-dimensional (Matrix definition) 
matrix_array = np.array([ [2,5,8], [7,3,6] ])
matrix_array

array([[2, 5, 8],
       [7, 3, 6]])

MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [3]:
multidimensional = np.array([ [3,7,9,3],[4,3,2,2] ])
multidimensional

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS 

In [10]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(12)
x

array([0.45002074, 0.69432381, 0.26689788, 0.62875906, 0.36098504,
       0.61537833, 0.07130182, 0.05415571, 0.45337982, 0.19266084,
       0.1570545 , 0.3824979 ])

In [11]:
# you can create a matrix of random number as well
x = np.random.rand(4,4)
x

array([[0.48722528, 0.3616872 , 0.1331811 , 0.86450863],
       [0.88385606, 0.49988524, 0.58499584, 0.39236789],
       [0.36700055, 0.06931687, 0.38408195, 0.7640886 ],
       [0.40351727, 0.61017632, 0.66986639, 0.65271333]])

In [21]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1,40)
x

29

In [26]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1,100,15)
x


array([ 3, 74, 50, 41, 43, 79, 30, 91, 88, 16, 87, 37, 93, 84,  1])

In [32]:
# np.arange creates an evenly spaced values within a given interval
y = np.arange(1,40)
y


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39])

In [34]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(7)
x

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [37]:
# Matrix of ones
x = np.ones((7,7))
x

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [38]:
# Array of zeros
y = np.zeros((4,4))
y

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [40]:
num = int(input("Enter an integer: "))
x = np.random.randint(0,num,10)
x

array([1, 5, 8, 9, 0, 2, 5, 3, 2, 7])

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [46]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
y = np.arange(1,10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
# Add 2 numpy arrays together
sum = x+y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [49]:
square = x**2
square

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [51]:
squareroot=np.sqrt(square)
squareroot

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [52]:
z = np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [60]:
x = np.array([5, 7, 20])
y= np.array([9, 15, 4])


dist = np.sqrt(y**2 + x**2)
dist

array([10.29563014, 16.55294536, 20.39607805])

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING 

In [63]:
x = np.array([4,7,10,12,15,20,30,40,60])
x

array([ 4,  7, 10, 12, 15, 20, 30, 40, 60])

In [64]:
# Access specific index from the numpy array
x[-1]

60

In [65]:
# Starting from the first index 0 up until and NOT including the last element
x[1:8]

array([ 7, 10, 12, 15, 20, 30, 40])

In [66]:
# Broadcasting, altering several values in a numpy array at once
x[-1] =25
x[0:3] =10
x

array([10, 10, 10, 12, 15, 20, 30, 40, 25])

In [68]:
# Let's define a two dimensional numpy array
x = np.random.randint(1,10,(4,4))
x

array([[2, 2, 6, 3],
       [3, 7, 3, 9],
       [7, 2, 9, 2],
       [9, 4, 2, 5]])

In [70]:
# Get a row from a mtrix
x[2]

array([7, 2, 9, 2])

In [71]:
# Get one element
x[2][-1]

2

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [77]:
X = np.array ([[2, 30, 20, -2,-4], [3, 4,  40, -3, -2], [-3, 4, -6, 90, 10], [25, 45, 34, 22, 12], [13, 24, 22, 32, 37]])
X[-1] = 0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [79]:
z = np.array([[4, 4, 3, 9, 6],
       [9, 9, 8, 9, 2],
       [4, 2, 1, 3, 3],
       [8, 1, 1, 6, 3],
       [1, 3, 6, 8, 8]])
z

array([[4, 4, 3, 9, 6],
       [9, 9, 8, 9, 2],
       [4, 2, 1, 3, 3],
       [8, 1, 1, 6, 3],
       [1, 3, 6, 8, 8]])

In [80]:
# numbers greater than 7
newz = z[z > 7]
newz

array([9, 9, 9, 8, 9, 8, 8, 8])

In [82]:
# Obtain odd elements only
oddz = z[z % 2 == 1]
oddz

array([3, 9, 9, 9, 9, 1, 3, 3, 1, 1, 3, 1, 3])

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [84]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4, 40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])
X[X < 0] = 0
X[X % 2 == 1] = -2
X

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [ ]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [2]:
import pandas as pd

In [90]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary
data = ({'Bank Client Id': [101, 102, 103, 104],
        'Bank Client Name': ['Alice', 'Bob', 'Charlie', 'Solomon'],
        'Net Worth': [45000, 78000, 62000, 24000],
        'Number of Years with Bank': [5, 8, 3,7]}) # the data in the dictionary

bank_df = pd.DataFrame(data)
bank_df

Bank Client Id Bank Client Name  Net Worth  Number of Years with Bank
0             101            Alice      45000                          5
1             102              Bob      78000                          8
2             103          Charlie      62000                          3
3             104          Solomon      24000                          7

In [92]:
# Let's obtain the data type 
type(bank_df)

pandas.core.frame.DataFrame

In [93]:
# you can only view the first couple of rows using .head()
bank_df.head(2)

Bank Client Id Bank Client Name  Net Worth  Number of Years with Bank
0             101            Alice      45000                          5
1             102              Bob      78000                          8

In [94]:
# you can only view the last couple of rows using .tail()
bank_df.tail(2)

Bank Client Id Bank Client Name  Net Worth  Number of Years with Bank
2             103          Charlie      62000                          3
3             104          Solomon      24000                          7

MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [34]:
portfolio = {'Ticker Symbol': ['INX', 'DJI', 'COMP', 'Gold'],
             'Number of Share': [100, 45, 69, 20],
             'Price per Share': [5117.09, 38714.77, 15973.17, 2164.5]}

portfolio_df = pd.DataFrame(portfolio)
portfolio_df

Ticker Symbol  Number of Share  Price per Share
0           INX              100          5117.09
1           DJI               45         38714.77
2          COMP               69         15973.17
3          Gold               20          2164.50

In [37]:
total_value = portfolio_df['Number of Share'] * portfolio_df['Price per Share']
print(total_value)
print("the total portfolio value is:",total_value.sum())

0     511709.00
1    1742164.65
2    1102148.73
3      43290.00
dtype: float64
the total portfolio value is: 3399312.38


# TASK #7: PANDAS WITH CSV AND HTML DATA

In [2]:
# Pandas is used to read a csv file and store data in a DataFrame
shopping_df = pd.read_csv('shopping_trends.csv')

In [3]:
shopping_df.head(5)

Customer ID  Age Gender Item Purchased  Category  Purchase Amount (USD)  \
0            1   55   Male         Blouse  Clothing                     53   
1            2   19   Male        Sweater  Clothing                     64   
2            3   50   Male          Jeans  Clothing                     73   
3            4   21   Male        Sandals  Footwear                     90   
4            5   45   Male         Blouse  Clothing                     49   

        Location Size      Color  Season  Review Rating Subscription Status  \
0       Kentucky    L       Gray  Winter            3.1                 Yes   
1          Maine    L     Maroon  Winter            3.1                 Yes   
2  Massachusetts    S     Maroon  Spring            3.1                 Yes   
3   Rhode Island    M     Maroon  Spring            3.5                 Yes   
4         Oregon    M  Turquoise  Spring            2.7                 Yes   

  Payment Method  Shipping Type Discount Applied Promo Code Used  \
0    Credit Card        Express              Yes             Yes   
1  Bank Transfer        Express              Yes             Yes   
2           Cash  Free Shipping              Yes             Yes   
3         PayPal   Next Day Air              Yes             Yes   
4           Cash  Free Shipping              Yes             Yes   

   Previous Purchases Preferred Payment Method Frequency of Purchases  
0                  14                    Venmo            Fortnightly  
1                   2                     Cash            Fortnightly  
2                  23              Credit Card                 Weekly  
3                  49                   PayPal                 Weekly  
4                  31                   PayPal               Annually

In [64]:
# Read tabular data using read_html


In [4]:
import pandas as pd

houseprice_df = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')
houseprice_df[0]

City  \
0                                      Vancouver, BC   
1                                       Toronto, Ont   
2                                        Ottawa, Ont   
3                                       Calgary, Alb   
4                                      Montreal, Que   
5                                        Halifax, NS   
6                                       Regina, Sask   
7                                    Fredericton, NB   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                 Average House Price  \
0                                         $1,036,000   
1                                           $870,000   
2                                           $479,000   
3                                           $410,000   
4                                           $435,000   
5                                           $331,000   
6                                           $254,000   
7                                           $198,000   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                     12 Month Change  
0                                           + 2.63 %  
1                                            +10.2 %  
2                                           + 15.4 %  
3                                            – 1.5 %  
4                                            + 9.3 %  
5                                            + 3.6 %  
6                                            – 3.9 %  
7                                            – 4.3 %  
8  (adsbygoogle = window.adsbygoogle || []).push(...

MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [9]:
retire_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retire_df[0]

Year of birth  \
0                                      1937 and prior   
1                                                1938   
2                                                1939   
3                                                1940   
4                                                1941   
5                                                1942   
6                                             1943-54   
7                                                1955   
8                                                1956   
9                                                1957   
10                                               1958   
11                                               1959   
12                                     1960 and later   
13  Notes: 1. Persons born on January 1 of any yea...   

                                                  Age  
0                                                  65  
1                                     65 and 2 months  
2                                     65 and 4 months  
3                                     65 and 6 months  
4                                     65 and 8 months  
5                                    65 and 10 months  
6                                                  66  
7                                     66 and 2 months  
8                                     66 and 4 months  
9                                     66 and 6 months  
10                                    66 and 8 months  
11                                   66 and 10 months  
12                                                 67  
13  Notes: 1. Persons born on January 1 of any yea...

# TASK #8: PANDAS OPERATIONS

In [21]:
# Let's define a dataframe as follows:

bankdata = ({'Bank Client Id': [101, 102, 103, 104],
        'Bank Client Name': ['Alice', 'Bob', 'Charlie', 'Solomon'],
        'Net Worth': [45000, 78000, 62000, 24000],
        'Number of Years with Bank': [5, 8, 3,7]})
client_df = pd.DataFrame(bankdata)
client_df

Bank Client Id Bank Client Name  Net Worth  Number of Years with Bank
0             101            Alice      45000                          5
1             102              Bob      78000                          8
2             103          Charlie      62000                          3
3             104          Solomon      24000                          7

In [25]:
# Pick certain rows that satisfy a certain criteria 
specificID= client_df[client_df['Bank Client Id'] == 102]
specificID

Bank Client Id Bank Client Name  Net Worth  Number of Years with Bank
1             102              Bob      78000                          8

In [18]:
# Delete a column from a DataFrame
client_df


Bank Client Name  Net Worth  Number of Years with Bank
0            Alice      45000                          5
1              Bob      78000                          8
2          Charlie      62000                          3
3          Solomon      24000                          7

MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [26]:
richNigga = client_df[ client_df['Net Worth'] > 50000]
richNigga

Bank Client Id Bank Client Name  Net Worth  Number of Years with Bank
1             102              Bob      78000                          8
2             103          Charlie      62000                          3

In [27]:
#getting the sum of that net worth
richNigga['Net Worth'].sum()

140000

# TASK #9: PANDAS WITH FUNCTIONS

In [71]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [29]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 
def networth_inc(amt):
    return amt*1.2

In [30]:
# You can apply a function to the DataFrame 
client_df['Net Worth'].apply(networth_inc)

0    54000.0
1    93600.0
2    74400.0
3    28800.0
Name: Net Worth, dtype: float64

In [31]:
#gets the length of the strings in each row
client_df['Bank Client Name'].apply(len)

0    5
1    3
2    7
3    7
Name: Bank Client Name, dtype: int64

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [43]:
portfolio_df

def triple(amt):
    z = (amt *3) + 200
    return z

result = portfolio_df['Price per Share'].apply(triple)
print(portfolio_df)
print(result)

print(result.sum())

  Ticker Symbol  Number of Share  Price per Share
0           INX              100          5117.09
1           DJI               45         38714.77
2          COMP               69         15973.17
3          Gold               20          2164.50
0     15551.27
1    116344.31
2     48119.51
3      6693.50
Name: Price per Share, dtype: float64
186708.59


# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [47]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [49]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by = 'Years with bank')

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [51]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
bank_client_df.sort_values(by = 'Years with bank', inplace= True)

In [83]:
# Set inplace = True to ensure that change has taken place in memory 


In [52]:
# Note that now the change (ordering) took place 
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [90]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [97]:
pd.concat([df1, df2, df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

# TASK #12: PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5 
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers) 
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

MINI CHALLENGE #1 SOLUTION: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [5]:
x = np.array([[[3, 7, 9, 3] , [4, 3, 2, 2]]])
x

array([[[3, 7, 9, 3],
        [4, 3, 2, 2]]])

MINI CHALLENGE #2 SOLUTION:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [15]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 10)
x

Please enter a positive integer value: 7


array([6, 5, 3, 5, 4, 2, 3, 3, 2, 1])

MINI CHALLENGE #3 SOLUTION:
- Given the X and Y values below, obtain the distance between them


```
X = [5, 7, 20]
Y = [9, 15, 4]
```




In [22]:
X = np.array([5, 7, 20])
Y = np.array([9, 15, 4])
Z = np.sqrt(X**2 + Y**2)
Z

array([10.29563014, 16.55294536, 20.39607805])

MINI CHALLENGE #4 SOLUTION:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [33]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [34]:
X[4] = 0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

MINI CHALLENGE #5 SOLUTION:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```

In [41]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X<0] = 0
X[X%2==1] = -2
X

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

MINI CHALLENGE #6 SOLUTION:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [58]:
portfolio_df = pd.DataFrame({'stock ticker symbols':['AAPL', 'AMZN', 'T'],
                             'price per share [$]':[3500, 200, 40], 
                             'Number of stocks':[3, 4, 9]})
portfolio_df

stock ticker symbols  price per share [$]  Number of stocks
0                 AAPL                 3500                 3
1                 AMZN                  200                 4
2                    T                   40                 9

In [59]:
stocks_dollar_value = portfolio_df['price per share [$]'] * portfolio_df['Number of stocks']
print(stocks_dollar_value)
print('Total portfolio value = {}'.format(stocks_dollar_value.sum()))

0    10500
1      800
2      360
dtype: int64
Total portfolio value = 11660


MINI CHALLENGE #7 SOLUTION:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [ ]:
# Read tabular data using read_html
retirement_age_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_age_df

MINI CHALLENGE #8 SOLUTION:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [ ]:
df_high_networth = bank_client_df[ (bank_client_df['Net worth [$]'] >= 5000) ]
df_high_networth

In [ ]:
df_high_networth['Net worth [$]'].sum()

MINI CHALLENGE #9 SOLUTION:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [77]:
def networth_update(balance):
    return balance * 3 + 200 

In [78]:
# You can apply a function to the DataFrame 
results = bank_client_df['Net worth [$]'].apply(networth_update)
results

0    10700
1    87200
2    30200
3     6200
Name: Net worth [$], dtype: int64

In [79]:
results.sum()

134300

PROJECT SOLUTION:

In [ ]:
# Creating a dataframe from a dictionary
# Let's define a dataframe with a list of bank clients with IDs = 1, 2, 3, 4, 5 

raw_data = {'Bank Client ID': ['1', '2', '3', '4', '5'],
            'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'], 
            'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']}

Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1


# Let's define another dataframe for a separate list of clients (IDs = 6, 7, 8, 9, 10)
raw_data = {
        'Bank Client ID': ['6', '7', '8', '9', '10'],
        'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'], 
        'Last Name': ['Christian', 'Mo', 'Steve', 'Bob', 'Michelle']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2


# Let's assume we obtained additional information (Annual Salary) about our bank customers 
# Note that data obtained is for all clients with IDs 1 to 10 
raw_data = {
        'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary


# Let's concatenate both dataframes #1 and #2
# Note that we now have client IDs from 1 to 10
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all


# Let's merge all data on 'Bank Client ID'
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all


In [104]:
new_client = {
        'Bank Client ID': ['11'],
        'First Name': ['Ry'], 
        'Last Name': ['Aly'],
        'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

Bank Client ID First Name Last Name  Annual Salary [$/year]
0             11         Ry       Aly                    1000

In [105]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df

Bank Client ID First Name  Last Name  Annual Salary [$/year]
0              1      Nancy        Rob                   25000
1              2       Alex        Ali                   35000
2              3       Shep     George                   45000
3              4        Max      Mitch                   48000
4              5      Allen      Steve                   49000
5              6       Bill  Christian                   32000
6              7       Dina         Mo                   33000
7              8      Sarah      Steve                   34000
8              9    Heather        Bob                   23000
9             10      Holly   Michelle                   22000
0             11         Ry        Aly                    1000